name: ci

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '**/README.md'
    - 'docs/**'

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '{{cookiecutter.python_version}}' # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel pipenv
        pipenv sync --dev
      env:
        {%- raw %}
        AZURE_DEVOPS_PAT: '${{ secrets.AZURE_DEVOPS_PAT }}'
        {%- endraw %}
    - name: isort
      run: |
        pipenv run isort . --check-only --diff
    # https://github.com/psf/black/issues/1664
    - name: black
      run: |
        pipenv run black . --check
    - name: flake8
      run: |
        pipenv run flake8
    - name: mypy
      run: |
        pipenv run mypy .
    {%- if cookiecutter.pyspark_version %}    
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'
    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '{{cookiecutter.pyspark_version}}'
        hadoop-version: '{{cookiecutter.hadoop_version}}'
    {%- endif %}
    - name: tests
      run: |
        pipenv run test
